name: wake-cloudtype
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch: {}
jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @cloudtype/cli
      - run: ctype login -t ${{ secrets.CLOUDTYPE_API_KEY }}
      - run: ctype update ip-check-app
